require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
permissions_path = '../node_modules/react-native-permissions/ios'

platform :ios, '11.0'

target 'PorterShopper' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'IQKeyboardManager'
  
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  
#  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
#
#  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
#
#  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
#
#
#
#  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  target 'PorterShopperTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
